### ISSUE TITLE
Property 'findLastIndex' does not exist on type 'lineDataItem[]'

### ISSUE THREAD

**Issue by stereodenis** [Abhinandan-Kushwaha/gifted-charts-core#31]
"gifted-charts-core": "^0.1.21" from "react-native-gifted-charts": "1.4.22"

<img width="773" alt="image" src="https://github.com/user-attachments/assets/37de5e61-cd5c-44c4-bc5a-adcc61b84c12">

**Comment by Abhinandan-Kushwaha** [comment]
Hi @stereodenis 
Thanks for reporting this issue.

It has been fixed with this PR- https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/33

**Comment by dumihi313** [comment]
Why don't we keep this code findLastIndex() ?
I can see it leads to low performance and wrong, even crash result
